### ISSUE TITLE
New columns for completed site: Escalation, Faction, and Loot

### ISSUE THREAD

**Issue by GoldenGnu** [burberius/pvetracker#23]
Added new columns to the completed sites view:
- Escalation
- Faction
- Loot (Have loot)

**Comment by burberius** [comment]
For faction and Escalation I would just display an icon. Do you have any ideas for icons to use? Perhaps something from https://fontawesome.com/ Those can be integrated quite easily.

**Comment by GoldenGnu** [comment]
I agree icons would be a good option, I would use icons from the eve image export collection: https://developers.eveonline.com/resource/resources

**Comment by burberius** [comment]
But those icons are only for items in game.
I thought about something like an explosion 💥 for escalation. And a medal 🥉 or police 📛 for the faction?

**Comment by GoldenGnu** [comment]
I think using emojis is a great idea, it’s supported by all major browsers and is just `:emoji_name:` really simple
