### ISSUE TITLE
Can't edit loot

### ISSUE THREAD

**Issue by GoldenGnu** [burberius/pvetracker#27]
When editing an site, the loot box will be empty, with no way to edit what you already entered. Additionally, adding the corrected loot just add it to the excising loot, I would expect to see the current loot and be able to remove/edit it too.

**Comment by GoldenGnu** [comment]
My suggestion would be to use the view layout for loot when editing. but with a X button at the end to remove it, and also have the loot textarea for adding new loot

**Comment by GoldenGnu** [comment]
![removeloot](https://user-images.githubusercontent.com/11528122/80868548-ac7e4f80-8c9b-11ea-96aa-67890ede711a.png)

**Comment by burberius** [comment]
I solved it be printing the loot in the text box, so it is possible to change it.
It's just the name and the quantity!
