### ISSUE TITLE
Use Contracts Appraisal API to get price for BPCs

### ISSUE THREAD

**Issue by GoldenGnu** [burberius/pvetracker#30]
BPC sometimes drops from sites, getting a price for them would be a nice addition.

Forum thread
https://forums.eveonline.com/t/contracts-appraisal-api-for-pricing-data-based-on-contracts/153149

Swagger specs:
https://app.swaggerhub.com/apis-docs/rihanshazih/contracts-appraisal/1.2.0

My Java client:
https://github.com/GoldenGnu/contracts-pricing

**Comment by burberius** [comment]
Added
